<div class="page-head"><div><span class="eyebrow dark"><?= e(tr('نمای کلی شبکه', 'Network overview')) ?></span><h1><?= e(tr('داشبورد', 'Dashboard')) ?></h1><p><?= e(tr('وضعیت کاربران، روترها و درآمد در یک نگاه', 'Users, routers and revenue at a glance')) ?></p></div><div class="head-actions"><a class="button primary" href="<?= e(url('user-form')) ?>">＋ <?= e(tr('کاربر جدید', 'New user')) ?></a></div></div>

<section class="metric-grid">
    <article class="metric-card blue"><span class="metric-icon">◉</span><div><small><?= e(tr('کل کاربران', 'Total users')) ?></small><strong><?= fa_digits($stats['total_users']) ?></strong><em><?= fa_digits($stats['active_users']) ?> <?= e(tr('فعال', 'active')) ?></em></div></article>
    <a class="metric-card green" href="<?= e(url('users',['status'=>'online'])) ?>"><span class="metric-icon">⌁</span><div><small><?= e(tr('آنلاین اکنون', 'Online now')) ?></small><strong><?= fa_digits($stats['online_users']) ?></strong><em><?= e(tr('نمایش کاربران دارای Session', 'View users with active sessions')) ?></em></div></a>
    <article class="metric-card amber"><span class="metric-icon">◷</span><div><small><?= e(tr('کاربران منقضی', 'Expired users')) ?></small><strong><?= fa_digits($stats['expired_users']) ?></strong><em><?= fa_digits($stats['overdue']) ?> <?= e(tr('فاکتور معوق', 'overdue invoices')) ?></em></div></article>
    <article class="metric-card violet"><span class="metric-icon">↗</span><div><small><?= e(tr('درآمد این ماه', 'Revenue this month')) ?></small><strong class="money-value"><?= money($stats['revenue']) ?></strong><em><?= money($stats['unpaid']) ?> <?= e(tr('مطالبات', 'outstanding')) ?></em></div></article>
</section>

<div class="content-grid two-thirds">
    <section class="panel"><div class="panel-head"><div><h2><?= e(tr('وضعیت روترها', 'Router status')) ?></h2><p><?= e(tr('آخرین همگام‌سازی و پایش', 'Latest synchronization and polling')) ?></p></div><a href="<?= e(url('routers')) ?>"><?= e(tr('مشاهده همه', 'View all')) ?> ←</a></div>
        <div class="table-wrap"><table><thead><tr><th><?= e(tr('روتر', 'Router')) ?></th><th><?= e(tr('آدرس', 'Host')) ?></th><th><?= e(tr('وضعیت', 'Status')) ?></th><th><?= e(tr('آخرین همگام‌سازی', 'Last sync')) ?></th></tr></thead><tbody>
        <?php foreach ($routers as $router): ?><tr><td><strong><?= e($router['name']) ?></strong></td><td dir="ltr"><?= e($router['host']) ?>:<?= e($router['port']) ?></td><td><span class="badge <?= badge_class($router['last_status']) ?>"><?= e(status_text($router['last_status'])) ?></span></td><td><?= e($router['last_sync_at'] ?: '—') ?></td></tr><?php endforeach; ?>
        <?php if (!$routers): ?><tr><td colspan="4" class="empty"><?= e(tr('هنوز روتری ثبت نشده است.', 'No routers configured yet.')) ?></td></tr><?php endif; ?>
        </tbody></table></div>
    </section>
    <section class="panel"><div class="panel-head"><div><h2><?= e(tr('ترافیک Interface', 'Interface traffic')) ?></h2><p><?= e(tr('دریافت مستقیم از RX/TX روتر', 'Direct RouterOS RX/TX counters')) ?></p></div></div>
        <form method="get" class="stack-form" data-auto-filter><input type="hidden" name="r" value="dashboard"><label><span><?= e(tr('روتر Internet PPPoE','Internet PPPoE router')) ?></span><select name="traffic_source"><option value="total" <?= $trafficSource==='total'?'selected':'' ?>><?= e(tr('مجموع Internet همه روترها','Total Internet — all routers')) ?></option><?php foreach($trafficInterfaces as $interface): $value=(string)$interface['router_id'];?><option value="<?= e($value) ?>" <?= $trafficSource===$value?'selected':'' ?>><?= e($interface['router_name'].' — Internet') ?><?= $interface['is_running']?' ●':'' ?></option><?php endforeach;?></select></label></form>
        <div class="traffic-total"><span class="traffic-ring"><b><?= fa_digits(number_format($stats['traffic_counter_total'] / 1073741824, 1)) ?></b><small>GiB</small></span></div>
        <div class="traffic-legend"><div><i class="dot blue-dot"></i><span>Rx Bytes</span><strong><?= fa_digits(number_format($stats['interface_rx']/1073741824, 2)) ?> GiB</strong></div><div><i class="dot green-dot"></i><span>Tx Bytes</span><strong><?= fa_digits(number_format($stats['interface_tx']/1073741824, 2)) ?> GiB</strong></div></div>
        <div class="traffic-legend"><div><span><?= e(tr('مصرف ثبت‌شده امروز','Traffic recorded today')) ?></span><strong><?= fa_digits(number_format(($stats['traffic_in']+$stats['traffic_out'])/1073741824,2)) ?> GiB</strong></div><div><span><?= e(tr('Total فعلی Interface','Current interface total')) ?></span><strong><?= fa_digits(number_format($stats['traffic_counter_total']/1073741824,2)) ?> GiB</strong></div></div>
        <?php $chartMax=1;foreach($trafficChart as $point){$chartMax=max($chartMax,(int)$point['rx'],(int)$point['tx']);} ?>
        <div class="traffic-chart"><?php foreach($trafficChart as $point):?><div class="chart-column"><div class="bars"><i class="in" style="height:<?= max(2,round(((int)$point['rx']/$chartMax)*100)) ?>%" title="RX <?= e(number_format((int)$point['rx']/1e6,1)) ?> MB"></i><i class="out" style="height:<?= max(2,round(((int)$point['tx']/$chartMax)*100)) ?>%" title="TX <?= e(number_format((int)$point['tx']/1e6,1)) ?> MB"></i></div><small><?= e($point['label']) ?></small></div><?php endforeach;?><?php if(!$trafficChart):?><p class="empty"><?= e(tr('پس از اولین نمونه‌برداری، نمودار اینجا نمایش داده می‌شود.','The chart appears after the first traffic samples.')) ?></p><?php endif;?></div>
    </section>
</div>

<section class="panel"><div class="panel-head"><div><h2><?= e(tr('آخرین فعالیت‌ها', 'Recent activity')) ?></h2><p><?= e(tr('رویدادهای ثبت‌شده مدیران و سیستم', 'Recent administrator and system events')) ?></p></div><?php if(Auth::isSuperadmin()):?><a href="<?= e(url('activity')) ?>"><?= e(tr('گزارش کامل', 'Full log')) ?> ←</a><?php endif;?></div>
    <div class="activity-list"><?php foreach($recent as $item):?><div class="activity-item"><span class="activity-dot"></span><div><strong><?= e($item['action']) ?></strong><small><?= e($item['admin_name'] ?: tr('سیستم','System')) ?> · <?= e($item['created_at']) ?></small></div></div><?php endforeach;?><?php if(!$recent):?><p class="empty"><?= e(tr('فعالیتی ثبت نشده است.','No activity recorded.')) ?></p><?php endif;?></div>
</section>
