<div class="page-head"><div><a class="back-link" href="<?= e(url('plans')) ?>">→ <?= e(tr('بازگشت به پلن‌ها','Back to plans')) ?></a><h1><?= e($pageTitle) ?></h1></div></div>
<form method="post" class="panel form-panel"><?= csrf_field() ?><div class="form-section"><h2><?= e(tr('مشخصات سرویس','Service details')) ?></h2><div class="form-grid">
<label><span><?= e(tr('روتر','Router')) ?> *</span><select name="router_id" required><option value=""><?= e(tr('انتخاب روتر','Select router')) ?></option><?php foreach($routers as $router):?><option value="<?= e($router['id']) ?>" <?= (int)($plan['router_id']??0)===(int)$router['id']?'selected':'' ?>><?= e($router['name']) ?></option><?php endforeach;?></select></label>
<label><span><?= e(tr('نام پلن','Plan name')) ?> *</span><input name="name" value="<?= e($plan['name']??'') ?>" required></label>
<label><span><?= e(tr('نام پروفایل در User Manager','User Manager profile name')) ?> *</span><input name="mikrotik_profile" dir="ltr" value="<?= e($plan['mikrotik_profile']??'') ?>" required></label>
<label><span><?= e(tr('محدودیت سرعت','Rate limit')) ?> *</span><input name="rate_limit" dir="ltr" value="<?= e($plan['rate_limit']??'') ?>" placeholder="10M/2M" required><small><?= e(tr('فرمت RouterOS، نمونه: دانلود/آپلود','RouterOS format, e.g. download/upload')) ?></small></label>
<label><span><?= e(tr('اعتبار (روز)','Validity in days')) ?> *</span><input type="number" min="1" name="validity_days" value="<?= e($plan['validity_days']??30) ?>" required></label>
<label><span><?= e(tr('قیمت','Price')) ?> *</span><input type="number" min="0" step="0.01" name="price" value="<?= e($plan['price']??0) ?>" required></label>
<label><span><?= e(tr('واحد پول','Currency')) ?> *</span><select name="currency"><option value="IRR" <?= ($plan['currency']??'IRR')==='IRR'?'selected':'' ?>>IRR</option><option value="IRT" <?= ($plan['currency']??'')==='IRT'?'selected':'' ?>>IRT</option><option value="USD" <?= ($plan['currency']??'')==='USD'?'selected':'' ?>>USD</option></select></label>
<label><span><?= e(tr('سقف حجم (GB)','Data cap in GB')) ?></span><input type="number" min="0" name="data_cap_gb" value="<?= e($plan['data_cap_gb']??'') ?>" placeholder="<?= e(tr('خالی = نامحدود','Blank = unlimited')) ?>"></label>
<label class="check-card inline-check"><input type="checkbox" name="is_active" value="1" <?= !isset($plan['is_active'])||!empty($plan['is_active'])?'checked':'' ?>><span><strong><?= e(tr('پلن فعال باشد','Plan is active')) ?></strong><small><?= e(tr('در فرم کاربر قابل انتخاب است','Available when creating users')) ?></small></span></label>
</div></div><div class="form-actions"><a class="button ghost" href="<?= e(url('plans')) ?>"><?= e(tr('انصراف','Cancel')) ?></a><button class="button primary"><?= e(tr('ذخیره پلن','Save plan')) ?></button></div></form>
