# Generated by Django 5.0.14 on 2026-07-25 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ppp_users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrafficLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("bytes_in", models.BigIntegerField(default=0)),
                ("bytes_out", models.BigIntegerField(default=0)),
                ("session_count", models.PositiveIntegerField(default=0)),
                ("uptime_seconds", models.BigIntegerField(default=0)),
                (
                    "local_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traffic_logs",
                        to="ppp_users.localuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="traffic_tra_date_bfb6f9_idx")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="trafficlog",
            constraint=models.UniqueConstraint(
                fields=("local_user", "date"), name="uniq_traffic_log_per_day"
            ),
        ),
    ]
