<div class="page-head"><div><a class="back-link" href="<?= e($id?url('user-detail',['id'=>$id]):url('users')) ?>">→ <?= e(tr('بازگشت','Back')) ?></a><h1><?= e($pageTitle) ?></h1><p><?= e($id?tr('تغییرات شبکه مستقیماً روی روتر اعمال می‌شود.','Network changes are applied directly to the router.'):tr('کاربر هم‌زمان روی روتر و پنل ساخته می‌شود و فاکتور می‌گیرد.','The user is created on the router and panel with an invoice.')) ?></p></div></div>
<?php if(!$routers||!$plans):?><div class="alert warning"><span>!</span><div><?= e(tr('برای ایجاد کاربر، حداقل یک روتر و یک پلن فعال لازم است.','At least one active router and plan are required.')) ?></div></div><?php endif;?>
<form method="post" class="panel form-panel" autocomplete="off"><?= csrf_field() ?><div class="form-section"><h2><?= e(tr('اطلاعات اتصال','Connection details')) ?></h2><div class="form-grid">
<?php if(!$id):?><label><span><?= e(tr('روتر','Router')) ?> *</span><select name="router_id" required><option value=""><?= e(tr('انتخاب کنید','Select')) ?></option><?php foreach($routers as $r):?><option value="<?= e($r['id']) ?>" <?= (int)($user['router_id']??0)===(int)$r['id']?'selected':'' ?>><?= e($r['name']) ?></option><?php endforeach;?></select></label><label><span><?= e(tr('نام کاربری PPP','PPP username')) ?> *</span><input name="username" dir="ltr" value="<?= e($user['username']??'') ?>" required pattern="[A-Za-z0-9_-]+"><small>A-Z, 0-9, _ , -</small></label><?php else:?><div class="readonly-field"><span><?= e(tr('نام کاربری','Username')) ?></span><strong dir="ltr"><?= e($user['username']) ?></strong></div><div class="readonly-field"><span><?= e(tr('روتر','Router')) ?></span><strong>#<?= e($user['router_id']) ?></strong></div><?php endif;?>
<label><span><?= $id?e(tr('رمز جدید (خالی = بدون تغییر)','New password (blank = unchanged)')):e(tr('رمز عبور','Password')).' *' ?></span><input name="password" type="password" dir="ltr" <?= $id?'':'required' ?>></label>
<label><span><?= e(tr('نوع سرویس','Service')) ?> *</span><select name="service" <?= $id?'disabled':'' ?>><?php foreach(['pppoe'=>'PPPoE','l2tp'=>'L2TP','sstp'=>'SSTP','pptp'=>'PPTP','any'=>'Any'] as $v=>$l):?><option value="<?= $v ?>" <?= ($user['service']??'pppoe')===$v?'selected':'' ?>><?= $l ?></option><?php endforeach;?></select><?php if($id):?><input type="hidden" name="service" value="<?= e($user['service']) ?>"><?php endif;?></label>
</div></div>
<div class="form-section"><h2><?= e(tr('پلن و سرعت','Plan and speed')) ?></h2><div class="form-grid"><label><span><?= e(tr('پلن','Plan')) ?> *</span><select name="plan_id" required><option value=""><?= e(tr('انتخاب کنید','Select')) ?></option><?php foreach($plans as $p):?><option value="<?= e($p['id']) ?>" <?= (int)($user['plan_id']??0)===(int)$p['id']?'selected':'' ?>><?= e($p['name']) ?> · <?= money($p['price'],$p['currency']) ?> · <?= fa_digits($p['validity_days']) ?> <?= e(tr('روز','days')) ?></option><?php endforeach;?></select></label><?php if($id):?><label><span><?= e(tr('سرعت سفارشی','Custom rate limit')) ?></span><input name="rate_limit" dir="ltr" value="<?= e($user['rate_limit']??'') ?>" placeholder="10M/2M"></label><?php endif;?></div></div>
<div class="form-section"><h2><?= e(tr('اطلاعات مشترک','Subscriber details')) ?></h2><div class="form-grid"><label><span><?= e(tr('نام کامل','Full name')) ?></span><input name="full_name" value="<?= e($user['full_name']??'') ?>"></label><label><span><?= e(tr('تلفن','Phone')) ?></span><input name="phone" dir="ltr" value="<?= e($user['phone']??'') ?>"></label><label class="wide-field"><span><?= e(tr('آدرس','Address')) ?></span><textarea name="address" rows="2"><?= e($user['address']??'') ?></textarea></label><label class="wide-field"><span><?= e(tr('یادداشت','Comment')) ?></span><textarea name="comment" rows="2"><?= e($user['comment']??'') ?></textarea></label></div></div>
<div class="form-actions"><a class="button ghost" href="<?= e($id?url('user-detail',['id'=>$id]):url('users')) ?>"><?= e(tr('انصراف','Cancel')) ?></a><button class="button primary" <?= !$routers||!$plans?'disabled':'' ?>><?= e($id?tr('ذخیره تغییرات','Save changes'):tr('ساخت کاربر و فاکتور','Create user and invoice')) ?></button></div></form>

