# Generated by Django 5.0.14 on 2026-07-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "mikrotik_profile",
                    models.CharField(
                        help_text="Must match a /ppp/profile name on the router",
                        max_length=100,
                    ),
                ),
                (
                    "rate_limit",
                    models.CharField(
                        help_text="RouterOS format, e.g. 10M/2M (down/up)",
                        max_length=50,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="IRR", max_length=3)),
                ("validity_days", models.PositiveIntegerField(default=30)),
                (
                    "data_cap_gb",
                    models.PositiveIntegerField(
                        blank=True, help_text="Blank = unlimited", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
