# Generated by Django 5.0.14 on 2026-07-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mikrotik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "host",
                    models.CharField(
                        help_text="IP or hostname, no scheme/port", max_length=255
                    ),
                ),
                ("port", models.PositiveIntegerField(default=443)),
                ("username", models.CharField(max_length=100)),
                ("password_encrypted", models.BinaryField(blank=True, null=True)),
                (
                    "use_api_key",
                    models.BooleanField(
                        default=False,
                        help_text="RouterOS 7.13+ API keys are preferred over Basic Auth",
                    ),
                ),
                ("api_key_encrypted", models.BinaryField(blank=True, null=True)),
                (
                    "tls_ca_cert",
                    models.TextField(
                        blank=True,
                        help_text="Pin the router's certificate (PEM). Leave blank to use system CAs.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="mikrotik",
            constraint=models.UniqueConstraint(
                fields=("host", "port"), name="uniq_mikrotik_host_port"
            ),
        ),
    ]
