# Generated by Django 5.0.14 on 2026-07-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mikrotik",
            name="use_tls",
            field=models.BooleanField(
                default=True,
                help_text="Keep enabled for any real router (credentials go over the wire otherwise). Only disable for a local plain-HTTP dev/test target such as the bundled mock server.",
            ),
        ),
    ]
