# Generated by Django 5.0.14 on 2026-07-25 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plans", "0001_initial"),
        ("routers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mikrotik_secret_id", models.CharField(blank=True, max_length=50)),
                ("username", models.CharField(max_length=100)),
                ("password_encrypted", models.BinaryField(blank=True, null=True)),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("pppoe", "PPPoE"),
                            ("pptp", "PPTP"),
                            ("l2tp", "L2TP"),
                            ("sstp", "SSTP"),
                        ],
                        default="pppoe",
                        max_length=10,
                    ),
                ),
                ("profile", models.CharField(blank=True, max_length=100)),
                ("rate_limit", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                            ("missing_on_device", "Missing on device"),
                            ("needs_plan_assignment", "Needs plan assignment"),
                        ],
                        default="active",
                        max_length=25,
                    ),
                ),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("full_name", models.CharField(blank=True, max_length=150)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("address", models.TextField(blank=True)),
                ("comment", models.TextField(blank=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mikrotik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_users",
                        to="routers.mikrotik",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="local_users",
                        to="plans.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["username"],
                "indexes": [
                    models.Index(
                        fields=["expiration_date"],
                        name="ppp_users_l_expirat_c9da1d_idx",
                    ),
                    models.Index(
                        fields=["status"], name="ppp_users_l_status_d276b5_idx"
                    ),
                    models.Index(
                        fields=["username"], name="ppp_users_l_usernam_435b81_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="localuser",
            constraint=models.UniqueConstraint(
                fields=("mikrotik", "username"), name="uniq_local_user_per_router"
            ),
        ),
    ]
